package uz.devops.domain.enumeration;

public enum BotState {
    EDIT_TASK,
    ENTER_TASK_NAME,
    ENTER_TASK_PRICE,
    ENTER_TASK_NEW_NAME,
    ENTER_TASK_NEW_PRICE,
    COMPLETED_CREATE_TASK,
    ENTER_TASK_DESCRIPTION,

    ENTER_JOB_NAME,
    ENTER_JOB_NEW_NAME,

    ENTER_ORDER_COUNT,
    ENTER_ORDER_DESCRIPTION,
    ENTER_NEW_PROFESSION_NAME,
    ENTER_NEW_USER_PHONE_NUMBER
}
